### ISSUE TITLE
Feedback on systems-of-eqns

### ISSUE THREAD

**Issue by paulmasson** [QBobWatson/gt-linalg#251]
In reference to version 5f9d00240bebd633057eaab6b1d13c8707d3fd73

Mathbox/Three.js examples break out of iframes on iOS upon first interaction with controls. Makes it impossible to read the immediately following text. 

Likely cause is a known bug in iOS handling of iframes. You probably need to set the iframes’ width and height explicitly from the computed style.

**Comment by QBobWatson** [comment]
Thanks for reporting the issue.  I can't actually reproduce it -- iframes seem to work fine on my iPhone -- has it been fixed in iOS since you opened the issue?

**Comment by paulmasson** [comment]
Testing on an iPad updated to iOS 12.3.1 and problem persists. The interactive graphics expand to the width of the screen. In portrait mode this just covers the captions of the graphics, but in landscape mode it covers much more text.

**Comment by QBobWatson** [comment]
The demo is styled to expand to 100% width when interacting.  To un-maximize you just tap outside the demo area.  Is that what’s happening on your end?

**Comment by paulmasson** [comment]
It is not: the demos do not un-maximize when tapping outside.

**Comment by QBobWatson** [comment]
I added a javascript snippet to reload the iframe on iOS when the demo is un-maximized.  While I was at it, I implemented a more traditional method for maximizing the demos.  You can find it on the [testing site](https://shadowfax.ultrametric.guru/gt-linalg/).  Does this fix it for you?

**Comment by paulmasson** [comment]
While I can change what is displayed on the test page with the drop-down menu, interaction with the graphic is otherwise disabled and there is no maximization.

**Comment by QBobWatson** [comment]
I don't understand -- are you saying you can't navigate to a page with demos, or you can't interact with the demos, or can't maximize them?

Everything works fine on my iPhone and iPad, running Safari and Chrome.

**Comment by paulmasson** [comment]
Just the test page: it does not allow interaction on my iPad with the latest iOS. Does it work on yours?

**Comment by QBobWatson** [comment]
I'm not sure what you mean by "test page".  The site I linked above is a complete mirror of the book.

I pushed the changes to the production site.  Does it work for you there?

**Comment by paulmasson** [comment]
Yes it does. Sorry for the confusion about the test site. Much better maximization/minimization. Thanks!
